<a href="https://colab.research.google.com/github/shequoiab/first_project/blob/main/Copy_of_Lesson386_2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

NumPy almost always get the alias: np

In [ ]:
import numpy as np

## Ways to Create NumPy Array


In [ ]:
# Creating a one-dimensional array with 5 elements
a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


## Ndarray Object


In [ ]:
#output <function numpy.array>
print(np.array)

a = np.array([1,2,3])
print(a)


<built-in function array>
[1 2 3]


## One-Dimensional Array

In [ ]:
# Creating a 1-dimensional NumPy array with 5 elements
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)


[1 2 3 4 5]


## One-Dimensional Array using arange()


In [ ]:
my_array = np.arange(1,30)
print(my_array)

print('\n')

# start and stop parameters set
x = np.arange(10,20,2)
print (x)

print('\n')

x = np.arange(-3, 10, 4, dtype=int)
print (x)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


[10 12 14 16 18]


[-3  1  5  9]


## Array Attributes


In [ ]:
my_array = np.array([[1, 2, 3, 4, 5], [69,58,74,32,9]])

# Accessing elements of the array using indexing
print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.dtype)


2
(2, 5)
10
int64


## Data Type Objects in NumPy


In [ ]:
dtype = np.dtype(np.int8)
print(dtype)

# Creating arrays with different data types
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)

arr_complex = np.array([1 + 2j, 3 + 4j], dtype=np.complex128)

# Checking the dtype attribute
print(arr_int32.dtype)     # Output: int32
print(arr_float64.dtype)   # Output: float64
print(arr_complex.dtype)   # Output: complex128


int8
int32
float64
complex128


## Multidimensional Array


In [ ]:
# Creating a 2-dimensional NumPy array with 3 rows and 2 columns
my_array = np.array([[1, 2], [3, 4], [5, 6]])
print(my_array)

print('\n')

# Creating a 2-dimensional NumPy array with 3 rows and 2 columns
my_array = np.array([[1, 2], [3, 4], [5, 6]])
print(my_array)


[[1 2]
 [3 4]
 [5 6]]


[[1 2]
 [3 4]
 [5 6]]


## Random Numbers in NumPy


In [ ]:
# Generates random numbers uniformly distributed between 0 and 1.
print(np.random.rand())
print(np.random.rand(3))
print('\n')

# Generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.
print(np.random.randn())
print(np.random.randn(3))
print('\n')

# Generates random integers between a specified range.
print(np.random.randint(20,25))
print(np.random.randint(100, 105))
print(np.random.randint(100, size=(5)))
print(np.random.randint(100, size=(5,3))) # Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
print('\n')

# Generates random samples from a given sequence.
print(np.random.choice([1,2,3,4,5]))

print('\n')
# Shuffles a sequence in place.
arr = [1,2,3,4,5]
print(np.random.shuffle(arr)) # retuns None suffles in place
print(np.random.permutation(arr)) # returns new shuffled copy


0.4817696389888557
[0.899644   0.82572288 0.6705803 ]


0.8311694166964128
[ 0.15132446 -1.19592341  0.14076652]


22
101
[53 80 33 47 57]
[[41 54 83]
 [77 55 75]
 [33  4 52]
 [29 95 20]
 [11 55 24]]


1


None
[4 1 5 3 2]


## Indexing and Slicing


In [ ]:
# Create a 1D numpy array
arr = np.array([1, 2, 3, 4, 5])

# Indexing: Access a specific element in the array
element = arr[2] # Returns the element at index 2 (which is 3)
print(element)

# Slicing: Access a range of elements in the array
slice = arr[1:4] # Returns elements at indices 1, 2, and 3
print(slice)


3
[2 3 4]


In [ ]:
# Creating a 1-dimensional NumPy array with 5 elements
my_array = np.array([1, 2, 3, 4, 5])

# Accessing elements of the array using indexing
print(my_array[0])  # Output: 1
print(my_array[3])  # Output: 4

1
4


In [ ]:
# Modifying elements of the array using indexing
my_array[2] = 7
print(my_array) # Output: [1 2 7 4 5]

# Accessing a subset of the array using slicing
print(my_array[1:4]) # Output: [2 7 4]

# Modifying a subset of the array using slicing
my_array[1:4] = np.array([6, 8, 9])
print(my_array)

# Output: [1 6 8 9 5]

[1 2 7 4 5]
[2 7 4]
[1 6 8 9 5]


## Arithmetic Operations

In [ ]:
# Create a 1D numpy array
arr = np.array([1, 2, 3])

# Perform arithmetic operations
sum_arr = arr + 1  # Element-wise sum with scalar 1
prod_arr = arr * 2 # Element-wise product with scalar 2
div_arr = arr / 2  # Element-wise division with scalar 2

# Print the results
print(sum_arr)
print(prod_arr)
print(div_arr)


[2 3 4]
[2 4 6]
[0.5 1.  1.5]


## Aggregate functions

In [ ]:
# Create a 1D numpy array
arr = np.array([1, 2, 3, 4, 5])

# Perform aggregate functions
arr_sum = np.sum(arr) # Sum of all elements
arr_mean = np.mean(arr) # Mean of all elements
arr_min = np.min(arr) # Minimum value
arr_max = np.max(arr) # Maximum value

# Print the results
print(arr_sum, arr_mean, arr_min, arr_max, sep=',' )


15,3.0,1,5


## Reshaping and Transposing

In [ ]:
# Create a 2D numpy array
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the matrix using numpy's attribute
transposed_matrix = matrix.T

# Reshape the transposed matrix into a 3x2 matrix
reshaped_matrix = transposed_matrix.reshape(3, 2)

# Print the original matrix, transposed matrix, and reshaped matrix
print("Original Matrix:")
print(matrix)
print(transposed_matrix)
print(reshaped_matrix)


## Transpose of a Matrix

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.transpose(A)
print(B)


[[1 3]
 [2 4]]


## Element-Wise Comparison

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 3, 3, 5])
c = a == b
print(c)


## Logical AND

In [ ]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
c = np.logical_and(a, b)
print(c) # Output: [ True False False False]


[ True False False False]


## Logical OR

In [ ]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
c = np.logical_or(a, b)

print(c)


[ True  True  True False]


Logical NOT

In [ ]:
a = np.array([True, False, True, False])
b = np.logical_not(a)

print(b)


[False  True False  True]


## Array-Wise Comparison


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 3, 3, 5])
c = np.array_equal(a, b)

print(c)


False


## Sorting

In [ ]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
b = np.sort(a)

print(b)


[1 1 2 3 3 4 5 5 6 9]


## Masking

In [ ]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
mask = a > 3
b = a[mask]
print(b)


[4 5 9 6 5]


## Searching and Counting


In [ ]:
arr = np.array([33, 2, 3,56,58,96,4,6,9,])
x = 3
print("Is 3 in the array?")
print(3 in arr)
print("The index of the minimum value:")
print(np.argmin(arr))
print("The index of the maximum value:")
print(np.argmax(arr))


Is 3 in the array?
True
The index of the minimum value:
1
The index of the maximum value:
5


## Counting


In [ ]:
# Example 1: Count non-zero elements in a 1D array
arr_1d = np.array([0, 5, 0, 8, 0, 3, 7, 0])
nonzero_count_1d = np.count_nonzero(arr_1d)

print("1D Array:", arr_1d)
print("Number of Non-Zero Elements:", nonzero_count_1d)

# Example 2: Count non-zero elements in a 2D array
arr_2d = np.array([[0, 2, 0, 4],
          [5, 0, 0, 8],
          [0, 0, 3, 0]])
nonzero_count_2d = np.count_nonzero(arr_2d)
print("2D Array:")
print(arr_2d)
print("Number of Non-Zero Elements:", nonzero_count_2d)


1D Array: [0 5 0 8 0 3 7 0]
Number of Non-Zero Elements: 4
2D Array:
[[0 2 0 4]
 [5 0 0 8]
 [0 0 3 0]]
Number of Non-Zero Elements: 5


## Find Unique Element or Value in 1D Array


In [ ]:
arr_1d = np.array([3, 1, 2, 3, 4, 2, 5, 1, 6, 4])
unique_elements_1d = np.unique(arr_1d)

print("1D Array:", arr_1d)
print("Unique Elements:", unique_elements_1d)

# Example 2: Find unique elements in a 2D array
arr_2d = np.array([[1, 2, 3],
          [4, 2, 5],
          [1, 6, 4]])
unique_elements_2d = np.unique(arr_2d)
print("2D Array:")
print(arr_2d)
print("Unique Elements:", unique_elements_2d)


1D Array: [3 1 2 3 4 2 5 1 6 4]
Unique Elements: [1 2 3 4 5 6]
2D Array:
[[1 2 3]
 [4 2 5]
 [1 6 4]]
Unique Elements: [1 2 3 4 5 6]


## NumPy Array Manipulation Functions

In [ ]:
arr1 = np.arange(4)
print('Elements of an array1:\n',arr1)
arr2 = np.arange(4,8)
print('Elements of an array2:\n',arr2)
res1 = arr1.reshape(2,2)
print('Reshaped array with 2x2 dimensions:\n',res1)
res2 = arr2.reshape(2,2)
print('Reshaped array with 2x2 dimensions:\n',res2)
print("Concatenation two arrays:\n")
concat = np.concatenate((arr1,arr2),axis=0)
print(concat)


Elements of an array1:
 [0 1 2 3]
Elements of an array2:
 [4 5 6 7]
Reshaped array with 2x2 dimensions:
 [[0 1]
 [2 3]]
Reshaped array with 2x2 dimensions:
 [[4 5]
 [6 7]]
Concatenation two arrays:

[0 1 2 3 4 5 6 7]
